name: Android build (using Gradle wrapper) and save APK to output/

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PUSH_TO_REPO: 'false'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Ensure wrapper is executable
        run: |
          if [ -f ./gradlew ]; then
            chmod +x ./gradlew
            echo "Using project gradlew wrapper"
          else
            echo "Gradle wrapper not found; failing the build. Please add gradle wrapper to repo (instructions in README)."
            exit 2
          fi

      - name: Build debug APK with wrapper
        run: |
          ./gradlew :app:assembleDebug --no-daemon --stacktrace
        timeout-minutes: 30

      - name: Create output dir and copy APK
        run: |
          mkdir -p output
          APK_PATH="app/build/outputs/apk/debug/app-debug.apk"
          if [ -f "$APK_PATH" ]; then
            cp "$APK_PATH" output/app-debug.apk
            ls -lh output || true
          else
            echo "APK not found at expected path: $APK_PATH"
            ls -la app/build || true
            exit 1
          fi

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-apk
          path: output/app-debug.apk

      - name: (Optional) Commit output/ to repo
        if: env.PUSH_TO_REPO == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add output/app-debug.apk || true
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "ci: add built debug apk to output/ [skip ci]" || true
            git push origin HEAD:main || true
          fi
